In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/mean_income/ilc_di17_1_Data.csv')

df.drop(labels=['Flag and Footnotes','INDIC_IL','UNIT'],axis = 1,inplace = True)
df.rename(columns={
        'TIME': 'Year', 
        'GEO': 'Nation',
        'Value': 'Mean income'
    }, inplace=True)
df.replace(':',np.nan, inplace=True)
df = df[(df.Year<2020) & (df.Year>=2017)]

df_income = df.copy()

In [5]:
df_income

      Year   Nation      DEG_URB      SEX                  AGE Mean income
2448  2017  Belgium       Cities    Males   Less than 18 years      21,131
2449  2017  Belgium       Cities    Males  From 18 to 64 years      24,516
2450  2017  Belgium       Cities    Males     18 years or over      23,960
2451  2017  Belgium       Cities    Males     60 years or over      23,186
2452  2017  Belgium       Cities    Males     65 years or over      21,287
...    ...      ...          ...      ...                  ...         ...
6115  2019   Serbia  Rural areas  Females  From 18 to 64 years       3,177
6116  2019   Serbia  Rural areas  Females     18 years or over       3,068
6117  2019   Serbia  Rural areas  Females     60 years or over       2,899
6118  2019   Serbia  Rural areas  Females     65 years or over       2,807
6119  2019   Serbia  Rural areas  Females     75 years or over       2,442

[3672 rows x 6 columns]

In [ ]:
df_income.to_csv('Data_cleaned')

In [3]:
df = pd.read_csv('Data/self-percieved-health/hlth_silc_18_1_Data.csv')
df.drop(labels=['Flag and Footnotes','UNIT'],axis = 1,inplace = True)
df.rename(columns={
        'TIME': 'Year', 
        'GEO': 'Nation',
        'Value': 'Percentage'
    }, inplace=True)
df.replace(':',np.nan, inplace=True)
df = df[(df.Year<2020) & (df.Year>=2017)]
#percentage è la percentuale di SEX in una certa AGE con un certo DEG_URB per un certo year in una certa Nation 
#che ritiene la sua health = Levels
df_health = df.copy()

In [6]:
df_health

,Year,Nation,DEG_URB,LEVELS,SEX,AGE,Percentage
34272,2017,Belgium,Cities,Very good,Males,From 16 to 24 years,61.0
34273,2017,Belgium,Cities,Very good,Males,From 25 to 29 years,54.8
34274,2017,Belgium,Cities,Very good,Males,From 25 to 34 years,47.3
34275,2017,Belgium,Cities,Very good,Males,From 35 to 44 years,38.4
34276,2017,Belgium,Cities,Very good,Males,From 45 to 54 years,24.7
...,...,...,...,...,...,...,...
85675,2019,Serbia,Rural areas,Bad or very bad,Females,From 65 to 74 years,37.5
85676,2019,Serbia,Rural areas,Bad or very bad,Females,65 years or over,50.8
85677,2019,Serbia,Rural areas,Bad or very bad,Females,From 75 to 84 years,64.1
85678,2019,Serbia,Rural areas,Bad or very bad,Females,75 years or over,66.5
85679,2019,Serbia,Rural areas,Bad or very bad,Females,85 years or over,75.5