In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/morti-tumori/hlth_cd_aro_1_Data.csv')
df.drop(labels=['Flag and Footnotes','UNIT','RESID'],axis = 1,inplace = True)
df.rename(columns={
        'TIME': 'Year', 
        'GEO': 'Nation',
        'ICD10': 'Disease',
        'Value': 'Number of deaths'
    }, inplace=True)
df.replace(':',np.nan, inplace=True)

In [3]:
df = df[(df.Year<2020) & (df.Year>=2017)]

In [4]:
df

,Year,Nation,Disease,AGE,SEX,Number of deaths
73500,2017,Belgium,Neoplasms,Less than 15 years,Males,39
73501,2017,Belgium,Neoplasms,Less than 15 years,Females,21
73502,2017,Belgium,Neoplasms,From 15 to 19 years,Males,15
73503,2017,Belgium,Neoplasms,From 15 to 19 years,Females,9
73504,2017,Belgium,Neoplasms,From 15 to 24 years,Males,30
...,...,...,...,...,...,...
183745,2019,Turkey,Non-malignant neoplasms (benign and uncertain),From 80 to 84 years,Females,142
183746,2019,Turkey,Non-malignant neoplasms (benign and uncertain),From 85 to 89 years,Males,135
183747,2019,Turkey,Non-malignant neoplasms (benign and uncertain),From 85 to 89 years,Females,113
183748,2019,Turkey,Non-malignant neoplasms (benign and uncertain),85 years or over,Males,180
183749,2019,Turkey,Non-malignant neoplasms (benign and uncertain),85 years or over,Females,156

In [5]:
df['Number of deaths'].isnull().sum()

8050

In [6]:
nations = df.Nation.unique()
years = df.Year.unique()

In [7]:
for nation in nations:
    df_nation = df[df.Nation == nation]
    for year in years:
        df_year = df_nation[df_nation.Year == year]
        print(nation,year, df_year['Number of deaths'].isnull().sum())

Belgium 2017 0
Belgium 2018 0
Belgium 2019 0
Bulgaria 2017 0
Bulgaria 2018 0
Bulgaria 2019 0
Czechia 2017 0
Czechia 2018 0
Czechia 2019 0
Denmark 2017 0
Denmark 2018 0
Denmark 2019 0
Germany (until 1990 former territory of the FRG) 2017 0
Germany (until 1990 former territory of the FRG) 2018 0
Germany (until 1990 former territory of the FRG) 2019 0
Estonia 2017 0
Estonia 2018 0
Estonia 2019 0
Ireland 2017 0
Ireland 2018 0
Ireland 2019 0
Greece 2017 0
Greece 2018 0
Greece 2019 0
Spain 2017 0
Spain 2018 0
Spain 2019 0
France 2017 0
France 2018 1050
France 2019 1050
France (metropolitan) 2017 0
France (metropolitan) 2018 1050
France (metropolitan) 2019 1050
Croatia 2017 0
Croatia 2018 0
Croatia 2019 0
Italy 2017 0
Italy 2018 0
Italy 2019 0
Cyprus 2017 100
Cyprus 2018 100
Cyprus 2019 150
Latvia 2017 0
Latvia 2018 0
Latvia 2019 0
Lithuania 2017 0
Lithuania 2018 0
Lithuania 2019 0
Luxembourg 2017 150
Luxembourg 2018 100
Luxembourg 2019 250
Hungary 2017 0
Hungary 2018 0
Hungary 2019 0
Malta 2017 150
Malta 2018 0
Malta 2019 100
Netherlands 2017 0
Netherlands 2018 0
Netherlands 2019 0
Austria 2017 0
Austria 2018 0
Austria 2019 0
Poland 2017 0
Poland 2018 0
Poland 2019 0
Portugal 2017 0
Portugal 2018 0
Portugal 2019 0
Romania 2017 0
Romania 2018 0
Romania 2019 0
Slovenia 2017 0
Slovenia 2018 0
Slovenia 2019 0
Slovakia 2017 0
Slovakia 2018 0
Slovakia 2019 0
Finland 2017 0
Finland 2018 0
Finland 2019 0
Sweden 2017 0
Sweden 2018 0
Sweden 2019 0
Iceland 2017 200
Iceland 2018 200
Iceland 2019 200
Liechtenstein 2017 400
Liechtenstein 2018 400
Liechtenstein 2019 300
Norway 2017 0
Norway 2018 0
Norway 2019 0
Switzerland 2017 0
Switzerland 2018 0
Switzerland 2019 0
United Kingdom 2017 0
United Kingdom 2018 0
United Kingdom 2019 1050
Serbia 2017 0
Serbia 2018 0
Serbia 2019 0
Turkey 2017 0
Turkey 2018 0
Turkey 2019 0

In [8]:
df.to_csv('Data_cleaned/EU-tumors.csv')